### ISSUE TITLE
Hello, is this compatible with 1.17?

### ISSUE THREAD

**Issue by carljen** [Rapha149/MessageHider#1]
Just updated my server to 1.17 and thought the plugin will work just fine but doesn't. Will you be planning to update this to 1.17?

Also thank you for making this plugin!

**Comment by Rapha149** [comment]
I also thought it should work so I did not look into it for now. I'll do it as fast as I can. Thank you for the report!

**Comment by Rapha149** [comment]
I patched it for 1.17. You can download the new file from Spigot now :slightly_smiling_face:

**Comment by carljen** [comment]
Thank you so much!
