### ISSUE TITLE
English Tutorial Corrections

### ISSUE THREAD

**Issue by TheNitram21** [Rapha149/MessageHider#3]
**Is this a new translation or a correction for an existing translation?**
Correction

**Which language?**
English

**Changes**
In line 24: Change *information* from singular to plural.
In line 104: Remove *Allgemein*.
In line 130: Change the *T* in *Text* to be lowercase (for consistency).
In line 146: Remove *counts* before *applies*.
In line 191: Add a space.
In line 220: Add a right angle bracket.
In line 270 and 271: Add indentations.
In line 281: Change the content of the brackets.
(And yes, I read through the whole tutorial just to find things that I can correct)

**Translated file**
[ENGLISH.md](https://github.com/Rapha149/MessageHider/files/8984182/ENGLISH.md)

**Comment by Rapha149** [comment]
Thanks for reviewing and nice to hear from you!
I agree with almost all changes, except the first. The word _information_ has no plural in Englisch. But I checked and yes, the sentence _A few information in advance_ does not make sense. I changed it to _A little bit of information in advance_.

Thank you for your time!
